---
- name: Update Security Patches on Ubuntu 24.04
  hosts: jenkins_server
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # กำหนด Python Interpreter
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Apply security updates only
      apt:
        upgrade: dist
        only_upgrade: yes

    - name: Clean up old packages
      apt:
        autoremove: yes
        autoclean: yes

    - name: reboot Server status
      ansible.builtin.debug:
        msg: "Reboot is set to {{reboot | default(false) }}"
    
    - name: reboot server if need
      ansible.builtin.reboot:
      when: reboot |grep default(false) | bool

    - name: Uptime Server
      ansible.builtin.command: uptime 
      register: uptime_output

    - name: show uptime result
      ansible.builtin.debug:
        msg: "{{ uptime_output.stdout }}"

      