---
- name: Update Security Patches on Ubuntu 24.04
  hosts: jenkins_server
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # กำหนด Python Interpreter

  tasks:
    - name: Import tasks Install Package
      import_task: common/install_package.yml

    - name: import_task clear_Package
      import_task: common/clear_package.yml
    
    - name: import_task Reboot 
      import_task: common/reboot.yml